perf: improve flashy loading when lazy loading
OneUptime/oneuptime pull request #1067
Opened 2023-12-13 16:18 UTC by soknaly

### Improve flashy loading when lazy loading

After introducing lazy loading, I noticed an unpleasant User Experience when the pages were loaded along with the sidebar. So instead of lazy loading the whole page, we only lazy load the sub-page which so the loading indicator only shows in the content panel at the right side of the sidebar.

Following `react-router-dom` v6, we can take advantage of `Outlet` to simplify this.

**This change include the following**
- Breadcrumbs link will be no longer specified on each page, instead, we use the function to build breadcrumbs links for each path map.
- Breadcrumbs are now generated by using the function `BuildBreadcrumbLinksByTitles`.
  - Project -> Monitors -> View Monitor -> Custom Fields represented by `/dashboard/:projectId/monitors/:id/custom-fields`
  - Breaking down breadcrumb with a link representation for each item (reversed)
     - Custom Fields = `/dashboard/:projectId/minitors/:id/custom-fields`
     - Project = `/dashboard/:projectId`
     - Monitors = `/dashboard/:projectId/monitors`

### Pull Request Checklist: 

- [ ] Please make sure all jobs pass before requesting a review. 
- [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [x] Have you lint your code locally before submission?
- [ ] Did you write tests where appropriate?

### Related Issue?

### Screenshots (if appropriate):

2023-12-13 16:29 UTC, soknaly commented
@simlarsen @nawazdhandala You can check this one if it makes sense, I can continue working on this for other pages.

If you have questions or concerns, please let me know.

Thank you

2023-12-13 18:55 UTC, nawazdhandala commented
Yes, please do.

2023-12-31 16:54 UTC, simlarsen commented
@soknaly  Thank you for all your work! Happy new year to you and family.

2024-01-01 06:41 UTC, soknaly commented
Thank you @simlarsen! Happy New Year to you and your family too 🎆

2024-01-03 09:05 UTC, simlarsen requested changes

2024-01-03 09:05 UTC, simlarsen commented on CommonUI/src/Utils/Navigation.ts
> +    public static getBreadcrumpRoute(level: number): Route {
typo

2024-01-03 09:08 UTC, simlarsen commented on CommonUI/src/Config.ts
> +export const BILLING_ENABLED: boolean = true;
or I can fix it. Not a big deal.

2024-01-03 09:08 UTC, simlarsen commented on CommonUI/src/Utils/Navigation.ts
> +    public static getBreadcrumpRoute(level: number): Route {
or I can fix it. Not a big deal.

2024-01-03 09:08 UTC, merged

2024-01-03 09:58 UTC, soknaly commented on CommonUI/src/Config.ts
> +export const BILLING_ENABLED: boolean = true;
@simlarsen Sorry forgot to rever this.