Tests for Alerts.tsx
OneUptime/oneuptime pull request #243
Opened 2022-08-16 15:48 UTC by yassineejjoud

Tests for CommonUI/src/Components/Alerts/Alert.tsx

![image](https://user-images.githubusercontent.com/40143980/184923038-1774586c-1add-45ea-8475-883ece3a3e59.png)

2022-08-16 17:54 UTC, simlarsen requested changes

2022-08-16 17:54 UTC, simlarsen commented on CommonUI/src/Tests/Alerts.test.tsx
> +                .findAllByType('div')[2]
You can id this div instead of array[2]

2022-08-16 17:54 UTC, simlarsen commented on CommonUI/src/Tests/Alerts.test.tsx
> +    const allElements = testInstance
Please do not use array[indexes], you can id the div.

2022-08-16 20:11 UTC, yassineejjoud commented on CommonUI/src/Tests/Alerts.test.tsx
> +                .findAllByType('div')[2]
Okay I will take care of that.

2022-08-16 21:01 UTC, yassineejjoud commented on CommonUI/src/Tests/Alerts.test.tsx
> +    expect(testInstance.findAllByType('strong')[0]?.props['children']).toEqual(
done

2022-08-16 21:01 UTC, yassineejjoud commented on CommonUI/src/Tests/Alerts.test.tsx
> +    const allElements = testInstance
done

2022-08-25 18:50 UTC, simlarsen commented
This PR is abandoned.

2022-08-25 18:50 UTC, closed without merging