Tests for Badge.tsx and Loader.tsx
OneUptime/oneuptime pull request #292
Opened 2022-10-20 15:37 UTC by yawMD

### Title of this pull request?

### Small Description?

### Pull Request Checklist: 

- [ ] Please make sure all jobs pass before requesting a review. 
- [ ] Assign yourself to the PR
- [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [ ] Label it as "needs-review"
- [ ] Have you lint your code locally before submission?
- [ ] Did you write tests where appropiate?

### Related Issue?

### Screenshots (if appropriate):

2022-10-21 20:29 UTC, simlarsen requested changes

2022-10-21 20:29 UTC, simlarsen commented on CommonUI/src/Tests/Loader.test.tsx
> +        expect(BarLoader).toBeInTheDocument;
isnt this a function?

2022-10-21 20:29 UTC, simlarsen commented on CommonUI/src/Tests/Loader.test.tsx
> +        expect(BeatLoader).toBeInTheDocument;
isnt this a function?

2022-10-21 21:22 UTC, yawMD commented on CommonUI/src/Tests/Loader.test.tsx
> +        expect(BarLoader).toBeInTheDocument;
yeah they are

2022-10-21 21:22 UTC, yawMD commented on CommonUI/src/Tests/Loader.test.tsx
> +        expect(BeatLoader).toBeInTheDocument;
sure is

2022-10-24 10:42 UTC, simlarsen commented on CommonUI/src/Tests/Loader.test.tsx
> +        expect(BarLoader).toBeInTheDocument;
then why dont you call it? toBeInTheDocument()

2022-10-24 13:55 UTC, yawMD commented on CommonUI/src/Tests/Loader.test.tsx
> +        expect(BarLoader).toBeInTheDocument;
changed

2022-10-25 18:20 UTC, simlarsen approved these changes

2022-10-25 18:21 UTC, merged