Add tests for Common/Types/*.ts
OneUptime/oneuptime pull request #403
Opened 2023-04-08 12:56 UTC by aphilas

### Add tests Common/Types/*.ts

### This PR adds tests Common/Types/*.ts

### Pull Request Checklist: 

- [x] Please make sure all jobs pass before requesting a review. 
- [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [x] Have you lint your code locally before submission?
- [x] Did you write tests where appropiate?

### Related Issue?

Closes #58 

### Screenshots (if appropriate):

2023-04-08 12:57 UTC, aphilas commented
For [`Common/Types/ArrayUtil.ts`](https://github.com/OneUptime/oneuptime/blob/master/Common/Types/ArrayUtil.ts), should I just test the _happy_ path in `ArrayUtil.isEqual`? For instance, a number of expected (or maybe unexpected) errors might occur such as:
- If a top-level element of the input arrays is a Symbol a `TypeError` is raised
- `BigInt` is not JSON serializable
- `Array.sort` compares strings in UTF-16 code units - top level `NaN`, `undefined`, `Infinity`, etc might yield unexpected results
- Cylic references

2023-04-08 12:58 UTC, aphilas commented
This PR excludes tests for [`Common/Types/JSONFunctions.ts`](https://github.com/OneUptime/oneuptime/blob/master/Common/Types/JSONFunctions.ts) as it appears elaborate enough to warrant it's own PR. I have opened #402 to track that.

2023-04-17 19:42 UTC, simlarsen requested changes

2023-04-18 08:20 UTC, aphilas commented on Common/Tests/Types/Role.test.ts
> +    'Owner',
Role is not a subset of Permission. Does this make more sense?

```ts
const expectedFields: Array<keyof typeof Role> = [
    'Owner',
    'Administrator',
    'Member',
    'Viewer',
    Permission.CanManageProjectBilling,
    Permission.CanCreateProjectTeam,
    Permission.CanEditProjectTeam,
    Permission.CanDeleteProjectTeam,
    Permission.CanCreateProjectLabel,
    Permission.CanEditProjectLabel,
    Permission.CanDeleteProjectLabel,
    'CanCreateProjectResources',
    'CanEditProjectResources',
    'CanDeleteProjectResources',
    Permission.User,
    Permission.Public,
];
```

In case is isn't clear, the array sets up a table-driven version of the `expect(Enum.Member).toBe('EnumMember')` idiom I've seen in other test files in the repo.

2023-04-18 11:31 UTC, aphilas commented on Common/Tests/Types/Sleep.test.ts
> +describe('Sleep', () => {
For just this file, or for all files?

2023-04-18 11:39 UTC, simlarsen commented on Common/Tests/Types/Role.test.ts
> +    'Owner',
I think Role.ts is deprectaed. Can you please delete the file and delete the test as well. I'm so sorry for this.

2023-04-18 11:46 UTC, aphilas commented on Common/Tests/Types/Role.test.ts
> +    'Owner',
Sure, I will delete the file. No worries.

2023-04-19 10:47 UTC, merged