Duplicate modal test
OneUptime/oneuptime pull request #855
Opened 2023-10-21 10:09 UTC by hammadfauz

### DuplicateModel tests

### Tests for the `DuplicateModel` component

### Pull Request Checklist: 

- [ ] Please make sure all jobs pass before requesting a review. 
- [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [ ] Have you lint your code locally before submission?
- [ ] Did you write tests where appropriate?

2023-10-23 11:53 UTC, simlarsen requested changes

2023-10-23 12:15 UTC, hammadfauz commented on CommonUI/src/Tests/__snapshots__/DuplicateModel.test.tsx.snap
> +exports[`DuplicateModel handles could not create error correctly 1`] = `
This is a snapshot file. Snapshots are an easy way to test how the UI "looks" at a certain state of a component. So instead of lots of assertions testing for various things like the presence of some text, some button, some styles, etc, we can just do a single assertion that the component DOM should match the snapshot.

More info [here](https://jestjs.io/docs/snapshot-testing).

2023-10-23 12:59 UTC, simlarsen requested changes

2023-10-23 12:59 UTC, simlarsen commented on CommonUI/src/Tests/__snapshots__/DuplicateModel.test.tsx.snap
> +exports[`DuplicateModel handles could not create error correctly 1`] = `
Please dont use snapshots. Only test out key elements in the UI as UI tends to change a lot.

2023-10-23 13:09 UTC, hammadfauz commented on CommonUI/src/Tests/__snapshots__/DuplicateModel.test.tsx.snap
> +exports[`DuplicateModel handles could not create error correctly 1`] = `
Got it. I will fix.

2023-10-23 14:19 UTC, hammadfauz commented on CommonUI/src/Tests/__snapshots__/DuplicateModel.test.tsx.snap
> +exports[`DuplicateModel handles could not create error correctly 1`] = `
removed snapshots. @simlarsen

2023-10-27 15:42 UTC, simlarsen requested changes

2023-10-27 15:42 UTC, simlarsen commented on CommonUI/src/Tests/Components/DuplicateModel.test.tsx
> +            document.querySelector('#payment-details-heading')?.textContent
please fix this id . It shouldnt be called this, please fix this in product code.

2023-10-27 15:42 UTC, simlarsen commented on CommonUI/src/Tests/Components/DuplicateModel.test.tsx
> +        expect(document.querySelector('h2')?.textContent).toBe('Duplicate Foo');
please id what you're querying and then select. Please do this for the rest of the file

2023-10-27 15:49 UTC, hammadfauz commented on CommonUI/src/Tests/Components/DuplicateModel.test.tsx
> +            document.querySelector('#payment-details-heading')?.textContent
Is `duplicate-model-details-heading` a suitable id?

2023-10-27 15:55 UTC, simlarsen commented on CommonUI/src/Tests/Components/DuplicateModel.test.tsx
> +            document.querySelector('#payment-details-heading')?.textContent
yeah!

2023-10-30 08:23 UTC, simlarsen approved these changes

2023-10-30 08:24 UTC, simlarsen approved these changes

2023-10-30 08:24 UTC, merged