Probe.test
OneUptime/oneuptime pull request #878
Opened 2023-11-10 13:34 UTC by slavaGanzin

2023-11-10 17:15 UTC, simlarsen approved these changes

2023-11-10 17:15 UTC, simlarsen commented on CommonUI/src/Tests/Components/Probe.test.tsx
> +        const iconElement: Element | null =
Can you please id these elements and refer to them by id instead.

2023-11-10 17:15 UTC, simlarsen requested changes
Please id these elements and refer to them by id.

2023-11-11 22:15 UTC, slavaGanzin commented
#799

2023-11-15 16:08 UTC, simlarsen approved these changes

2023-11-15 16:08 UTC, merged