Adds tests for Common/Types/Database
OneUptime/oneuptime pull request #885
Opened 2023-11-15 16:08 UTC by koox00

### Adds tests for Common/Types/Database.

Adds new tests for some of the files in Common/Types/Database directory.
Refactored one test for simplicity and test coverage.

Upon writing the tests I noticed a couple of issues.

1. IsPermissionsIf decorator didn't set the property due to the initial property value in the BaseModel. Moved the initialization to the constructor and to set only if there isn't a value, to fix this.
2. Classes that extend CompareBase, AKA classes that take either a number or a Date as value, "fail" serialization and de-serialization. The value in the end object is a string. This commit attempts to fix that as well.

PS: I used Date.toJSON() as it is the method that JSON.stringify would call on a date.

### Pull Request Checklist: 

- [ ] Please make sure all jobs pass before requesting a review. 
- [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [ ] Have you lint your code locally before submission?
- [ ] Did you write tests where appropriate?

### Related Issue

#210

2023-11-15 17:21 UTC, koox00 commented
@simlarsen it might be a better handling for parsing values that are `number` | `Date`.
Instead of handling this individually we could use the "reviver" function of `JSON.parse` and parse date strings to dates once, wdyt?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#the_reviver_parameter

2023-11-15 19:29 UTC, simlarsen requested changes

2023-11-15 19:29 UTC, simlarsen commented on Common/Types/Database/GreaterThan.ts
> +            value = (this as GreaterThan).toNumber();
This is not the right way to do it. Please it it in a way no exception is thrown.

2023-11-15 19:29 UTC, simlarsen commented on Common/Types/Database/GreaterThan.ts
> +            if (isNaN(Number(json['value']))) {
Really really hard to read.

2023-11-15 21:46 UTC, koox00 commented on Common/Types/Database/GreaterThan.ts
> +            value = (this as GreaterThan).toNumber();
oh sorry, I had added the `isNumber` method to `CompareBase` to use them here, and forgot...

2023-11-19 14:09 UTC, simlarsen requested changes

2023-11-19 14:09 UTC, simlarsen commented on Common/Types/Database/GreaterThan.ts
> +            const numValue: number = Number(json['value']);
This can be written a lot better in terms of readability.

2023-11-19 14:09 UTC, simlarsen commented on Common/Types/Database/LessThan.ts
> +        let value: number | string;
This can be written a lot better in terms of readability.

2024-10-22 12:54 UTC, closed without merging